package exceptions;


public class Demo2 
{
	public static void main(String[] args)
	{
		System.out.println("main start");
		m1();
		System.out.println("main end");
	}
	
	public static void m1()
	{
		System.out.println("m1 start");
		m2();
		System.out.println("m1 end");
		
	}
	
	public static void m2()
	{
		System.out.println("m2 start");
		try {
			System.out.println(10/0);
		} catch (Exception e) {
			// TODO: handle exception
		}	
		System.out.println("m2 end");
	}

}
